---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: talosconfig-worker
  namespace: {{ .Values.cluster.name }}
  labels:
    cluster-name: {{ .Values.cluster.name }}
    {{- include "cluster-chart.labels" . | nindent 4 }}
spec:
  template:
    spec:
      generateType: worker
      talosVersion: {{ .Values.cluster.talos_version }}
      strategicPatches:
        - |
          machine:
            install:
              disk: {{ .Values.machine.installDisk }}
              image: {{ .Values.cluster.image }}
              wipe: true
            {{- if eq .Values.storage "in-cluster" }}
            kernel:
              modules:
                - name: drbd
                  parameters:
                    - usermode_helper=disabled
                - name: drbd_transport_tcp
            {{- end }}
            kubelet:
              extraArgs:
                rotate-server-certificates: true
                cloud-provider: external
            {{- if eq .Values.storage "in-cluster" }}
            sysctls:
              vm.max_map_count: 262144
            {{- end }}
            {{- with .Values.registries }}
            registries:
            {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- if eq .Values.cni "cilium" }}
          cluster:
            network:
              cni:
                name: none
            proxy:
              disabled: true
          {{- end }}
